name: Ubuntu

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential liblz4-dev libzstd-dev protobuf-compiler doxygen graphviz gcovr
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCODE_COVERAGE=ON
      - name: Build
        run: cmake --build ${{github.workspace}}/build -j3
      - name: Run Tests
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure
      - name: Generate Coverage Report
        run: gcovr -r . ${{github.workspace}}/build
      # TODO add coverage report upload so contributors are encouraged to add tests during a PR
